### ISSUE TITLE
docker bifromq:3.0.2版本集群搭建，集群模式不可用！

### ISSUE THREAD

**Issue by xiaonannet** [bifromqio/bifromq#85]
**Describe the bug**

问题：构建成功后的集群，主节点可以连接，从节点不可连接。

三个节点均打印了构建集群成功的日志
`2024-05-09 12:15:40.685  INFO   [ForkJoinPool.commonPool-worker-1] --- c.b.bifromq.starter.StandaloneStarter   [StandaloneStarter.java:217] AgentHost joined seedEndpoint: b1:18899,b2:18899,b3:18899
2024-05-09 12:16:26.250  INFO   [main] --- c.b.bifromq.starter.StandaloneStarter   [StandaloneStarter.java:557] Standalone broker started

`

**Expected behavior**

**Logs**
三个节点日志
![image](https://github.com/bifromqio/bifromq/assets/57425893/3e19ade5-9785-4a2e-b3cc-a303f6899287)
![image](https://github.com/bifromqio/bifromq/assets/57425893/e092338a-3eb5-462e-bd25-0ebabfe9629d)

![image](https://github.com/bifromqio/bifromq/assets/57425893/f8577d6b-b643-4824-87d3-5d15ca32e4e9)
![image](https://github.com/bifromqio/bifromq/assets/57425893/8a973c03-e703-448e-afb9-7ac68c5ef116)

![image](https://github.com/bifromqio/bifromq/assets/57425893/9977b260-e826-43e5-95ee-411f923af7cc)
![image](https://github.com/bifromqio/bifromq/assets/57425893/1ece9bfe-b2ab-4f81-81bf-ac6ae51f3ce5)

**HOST**
- CPU:  2C4G
- Memory: [e.g. 32G]

**OS(please complete the following information):**
 - OS: Rocky Linux 9.3 Docker 

**JVM:**
- Version: [e.g. 17]
- Arguments: [e.g. if override any JVM arguments]

**BifroMQ**
- Version: bifromq-3.0.2

**Comment by popduke** [comment]
BifroMQ集群间通信会用到以下`host:port`：
```
clusterConfig
  host
  port
rpcServerConfig
  host
  port
baseKVServerConfig
  host
  port
```
通过docker搭建集群，你需要保证container内这几个`host:port`组合能正常通讯。

**Comment by wei-yk** [comment]
![image](https://github.com/bifromqio/bifromq/assets/68261120/2577c40d-ec9b-4486-bebb-f390aa443d35)
以指定端口，并映射。还是只有引导节点可以连接。

**Comment by popduke** [comment]
'b1','b2','b3'这几个地址在容器内和容器外分别解析到什么地址？，你用工具验证过容器内可以互向访问？

**Comment by wei-yk** [comment]
容器内解析的是公网ip地址。容器内互相访问是指什么

**Comment by xiaonannet** [comment]
> 'b1','b2','b3'这几个地址在容器内和容器外分别解析到什么地址？，你用工具验证过容器内可以互向访问？

全部在公网阿里云ECS环境下测试，'b1','b2','b3'映射的三个服务器公网IP，容器内解析的ip地址可以相互互通，所涉及端口均已放行，网络模式：host network、bridge 都尝试了不行，后尝试了腾讯ECS一样的结果：3个节点都输出 构建集群成功日志，只有引导节点可连接。

**Comment by popduke** [comment]
你试下把host直接指定成ip的方式？
我在单个host上用user-defined bridge network构建3节点集群没什么问题，都能连上: 

Docker cmd 
```
docker network create bifromq_dev
docker run -d -m 2G -e MEM_LIMIT='2147483648' --name bifromq_node1 --network bifromq_dev -p 1883:1883 -v ./node1_config.yml:/usr/share/bifromq/conf/standalone.yml bifromq/bifromq:latest
docker run -d -m 2G -e MEM_LIMIT='2147483648' --name bifromq_node2 --network bifromq_dev -p 2883:1883 -v ./node2_config.yml:/usr/share/bifromq/conf/standalone.yml bifromq/bifromq:latest
docker run -d -m 2G -e MEM_LIMIT='2147483648' --name bifromq_node3 --network bifromq_dev -p 3883:1883 -v ./node3_config.yml:/usr/share/bifromq/conf/standalone.yml bifromq/bifromq:latest
```

node1_config
```
bootstrap: false
clusterConfig:
  host: <NODE1_IP>
  port: 8899
  seedEndpoints: NODE1_IP:8899,NODE2_IP:8899,NODE3_IP:8899
```

node2_config
```
bootstrap: false
clusterConfig:
  host: <NODE2_IP>
  port: 8899
  seedEndpoints: NODE1_IP:8899,NODE2_IP:8899,NODE3_IP:8899
```

node3_config
```
bootstrap: false
clusterConfig:
  host: <NODE3_IP>
  port: 8899
  seedEndpoints: NODE1_IP:8899,NODE2_IP:8899,NODE3_IP:8899
```
